@id = bill uuid

### Get bill
GET http://localhost:8081/api/bills/{{id}}

### Get history info
GET http://localhost:8081/api/history
Sender-Address: UQDQbRJs32yYxOy-ZscoZ9Tlj_pH6D0jeS7a8U5oSkzkicwR

### Create bill
POST http://localhost:8081/api/bills
Content-Type: application/json
Sender-Address: UQDQbRJs32yYxOy-ZscoZ9Tlj_pH6D0jeS7a8U5oSkzkicwR

{
  "goal": "100000000000",
  "destination_address": "UQDQbRJs32yYxOy-ZscoZ9Tlj_pH6D0jeS7a8U5oSkzkicwR"
}

### Create tranasaction
POST http://localhost:8081/api/bills/{{id}}/transactions
Content-Type: application/json
Sender-Address: UQDQbRJs32yYxOy-ZscoZ9Tlj_pH6D0jeS7a8U5oSkzkicwR

{
  "amount": "10000",
  "op_type": "CONTRIBUTE"
}




